services:
  db:
    container_name: sakila-db
    image: mysql:8.0.28
    platform: linux/x86_64
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
    volumes:
      - ./sakila-db:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/docker.cnf
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_USER: "momotaro98"
      MYSQL_PASSWORD: "momotaro98"
    ports:
      - 33060:3306
